export default `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>NE7-SQL — Enterprise Cloud Database</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
@property --angle { syntax:'<angle>'; initial-value:0deg; inherits:false; }
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#060608;--surface:rgba(17,17,20,.72);--surface2:rgba(24,24,28,.85);--surface3:#1F1F23;--border:rgba(255,255,255,.06);--border2:rgba(255,255,255,.12);--text:#FAFAFA;--text2:#A1A1AA;--text3:#71717A;--accent:#818CF8;--accent2:#C084FC;--accent3:#38BDF8;--accentGlow:rgba(129,140,248,.16);--green:#34D399;--red:#F87171;--amber:#FBBF24;--radius:16px;--radius-sm:10px;--shadow-lg:0 8px 40px rgba(0,0,0,.5);--ease:cubic-bezier(.4,0,.2,1);--ease-out:cubic-bezier(.16,1,.3,1)}
html{font-size:15px}body{font-family:'Inter',system-ui,sans-serif;background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden;-webkit-font-smoothing:antialiased}
::selection{background:var(--accent);color:#fff}::-webkit-scrollbar{width:6px;height:6px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:var(--surface3);border-radius:3px}button{font-family:inherit}
#bg-canvas{position:fixed;inset:0;z-index:0;pointer-events:none}.grid-overlay{position:fixed;inset:0;z-index:0;pointer-events:none;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:56px 56px;mask-image:radial-gradient(ellipse 90% 70% at 50% 0%,black 30%,transparent 90%)}.noise{position:fixed;inset:0;z-index:1;pointer-events:none;opacity:.035;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}.aurora{position:fixed;top:0;left:0;right:0;height:2px;z-index:60;background:linear-gradient(90deg,transparent,var(--accent),var(--accent2),var(--accent3),transparent);background-size:200% 100%;animation:auroraSlide 6s linear infinite;opacity:.7}@keyframes auroraSlide{0%{background-position:0% 0}100%{background-position:200% 0}}
.boot{position:fixed;inset:0;z-index:500;background:var(--bg);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:24px;transition:opacity .6s var(--ease),visibility .6s}.boot.hidden{opacity:0;visibility:hidden;pointer-events:none}.boot-logo{width:56px;height:56px;border-radius:14px;background:linear-gradient(135deg,var(--accent),var(--accent2));display:flex;align-items:center;justify-content:center;box-shadow:0 0 40px var(--accentGlow);animation:bootPulse 1.6s var(--ease) infinite}.boot-logo svg{width:28px;height:28px;stroke:#fff;fill:none;stroke-width:2}@keyframes bootPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.06);box-shadow:0 0 70px rgba(129,140,248,.4)}}.boot-text{font-size:.8rem;color:var(--text3);letter-spacing:.2em;text-transform:uppercase;font-weight:600}.boot-bar{width:200px;height:2px;background:var(--surface3);border-radius:1px;overflow:hidden}.boot-bar-fill{height:100%;width:0%;background:linear-gradient(90deg,var(--accent),var(--accent2));transition:width 1.2s var(--ease-out)}
.screen{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:16px;position:relative;z-index:2}
.auth-card{background:var(--surface2);border:1px solid var(--border);border-radius:20px;padding:36px;width:100%;max-width:420px;backdrop-filter:blur(20px);box-shadow:var(--shadow-lg)}.auth-card h1{font-size:1.3rem;margin-bottom:6px;letter-spacing:-.02em}.auth-card p{color:var(--text3);font-size:.85rem;margin-bottom:22px}.switch-line{margin-top:14px;font-size:.78rem;color:var(--text3);text-align:center}.switch-line a{color:var(--accent);cursor:pointer}
.field{margin-bottom:16px}.field label{display:block;font-size:.75rem;font-weight:600;color:var(--text2);margin-bottom:6px}.field input{width:100%;padding:11px 14px;background:var(--bg);border:1px solid var(--border);border-radius:10px;color:var(--text);font-size:.9rem;outline:none;transition:all .25s var(--ease)}.field input:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accentGlow)}
.app{display:flex;min-height:100vh;position:relative;z-index:2}.sidebar{width:240px;position:fixed;top:0;left:0;bottom:0;background:rgba(10,10,12,.85);backdrop-filter:blur(24px) saturate(1.4);border-right:1px solid var(--border);display:flex;flex-direction:column;z-index:100;padding:20px 12px;transition:transform .35s var(--ease-out)}.main{flex:1;margin-left:240px;padding:32px 40px;max-width:1400px;width:100%}
.mobile-topbar{display:none;position:fixed;top:0;left:0;right:0;height:56px;background:rgba(6,6,8,.85);backdrop-filter:blur(20px);border-bottom:1px solid var(--border);z-index:90;align-items:center;justify-content:space-between;padding:0 16px}.menu-btn{background:none;border:none;color:var(--text);cursor:pointer;padding:8px;border-radius:8px;display:flex}.menu-btn svg{width:22px;height:22px;stroke:currentColor;fill:none;stroke-width:2}.mobile-logo{font-weight:700}.sidebar-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.4);z-index:95;opacity:0;visibility:hidden;transition:.3s}.sidebar-backdrop.active{opacity:1;visibility:visible}
.logo{display:flex;align-items:center;gap:10px;padding:8px 12px;margin-bottom:32px}.logo-mark{width:28px;height:28px;border-radius:8px;background:linear-gradient(135deg,var(--accent),var(--accent2));display:flex;align-items:center;justify-content:center;box-shadow:0 0 20px var(--accentGlow);position:relative}.logo-mark::after{content:'';position:absolute;inset:-3px;border-radius:11px;background:conic-gradient(from var(--angle),transparent 60%,var(--accent),transparent);animation:spin 4s linear infinite;opacity:.5;z-index:-1}@keyframes spin{to{--angle:360deg}}.logo-mark svg{width:16px;height:16px;stroke:#fff;fill:none;stroke-width:2}.logo-text{font-weight:700;font-size:.95rem;letter-spacing:-.02em}.logo-text span{color:var(--text3);font-weight:400;font-size:.72rem;margin-left:6px}
.nav-section{margin-bottom:24px}.nav-label{font-size:.65rem;text-transform:uppercase;letter-spacing:.12em;color:var(--text3);padding:0 12px;margin-bottom:8px;font-weight:600}.nav-item{display:flex;align-items:center;gap:10px;padding:10px 12px;border-radius:var(--radius-sm);color:var(--text2);cursor:pointer;transition:all .25s var(--ease);font-size:.85rem;font-weight:500;position:relative;margin-bottom:2px}.nav-item:hover{background:rgba(255,255,255,.04);color:var(--text);transform:translateX(2px)}.nav-item.active{background:var(--accentGlow);color:var(--accent)}.nav-item.active::before{content:'';position:absolute;left:0;top:50%;transform:translateY(-50%);width:3px;height:16px;background:var(--accent);border-radius:0 3px 3px 0;box-shadow:0 0 10px var(--accent)}.nav-item svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:1.8;flex-shrink:0}.nav-badge{margin-left:auto;background:var(--surface3);color:var(--text3);font-size:.65rem;padding:2px 7px;border-radius:5px;font-weight:600}.sidebar-footer{margin-top:auto;padding:12px;border-top:1px solid var(--border)}.status-pill{display:flex;align-items:center;gap:8px;font-size:.75rem;color:var(--text2)}.status-dot{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 8px var(--green);animation:pulse 2s infinite}@keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.4;transform:scale(.85)}}
.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:28px;gap:16px;flex-wrap:wrap}.header h1{font-size:1.7rem;font-weight:800;letter-spacing:-.03em;background:linear-gradient(135deg,#fff,#A1A1AA);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.header-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.btn{display:inline-flex;align-items:center;gap:7px;padding:9px 16px;border-radius:var(--radius-sm);font-size:.82rem;font-weight:600;cursor:pointer;transition:all .25s var(--ease);border:1px solid transparent;position:relative;overflow:hidden}.btn svg{width:14px;height:14px;stroke:currentColor;fill:none;stroke-width:2}.btn-primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;box-shadow:0 2px 16px var(--accentGlow)}.btn-primary:hover{transform:translateY(-2px);box-shadow:0 6px 28px rgba(129,140,248,.4)}.btn-ghost{background:var(--surface);border-color:var(--border);color:var(--text2);backdrop-filter:blur(10px)}.btn-ghost:hover{border-color:var(--accent);color:var(--text);transform:translateY(-1px)}.btn-danger{background:rgba(248,113,113,.08);color:var(--red);border-color:rgba(248,113,113,.2)}.btn-danger:hover{background:rgba(248,113,113,.18)}.btn-amber{background:rgba(251,191,36,.08);color:var(--amber);border-color:rgba(251,191,36,.2)}.btn-amber:hover{background:rgba(251,191,36,.18)}.btn-sm{padding:6px 10px;font-size:.72rem}.ripple{position:absolute;border-radius:50%;background:rgba(255,255,255,.35);transform:scale(0);animation:rippleAnim .6s var(--ease-out);pointer-events:none}@keyframes rippleAnim{to{transform:scale(4);opacity:0}}
.bento{display:grid;grid-template-columns:repeat(12,1fr);gap:16px;margin-bottom:32px}.card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:24px;transition:transform .3s var(--ease),border-color .3s,box-shadow .3s;position:relative;overflow:hidden;backdrop-filter:blur(20px);transform-style:preserve-3d}.card::before{content:'';position:absolute;inset:0;background:radial-gradient(500px circle at var(--mx,50%) var(--my,50%),rgba(129,140,248,.09),transparent 45%);opacity:0;transition:opacity .4s;pointer-events:none;z-index:1}.card:hover{border-color:var(--border2);box-shadow:var(--shadow-lg),0 0 40px var(--accentGlow)}.card:hover::before{opacity:1}.card > *{position:relative;z-index:2}.span-3{grid-column:span 3}.span-12{grid-column:span 12}
.stat-card{display:flex;flex-direction:column;gap:12px}.stat-header{display:flex;justify-content:space-between;align-items:center}.stat-icon{width:34px;height:34px;border-radius:9px;display:flex;align-items:center;justify-content:center;transition:transform .3s var(--ease)}.card:hover .stat-icon{transform:scale(1.1) rotate(-4deg)}.stat-icon svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:2}.stat-icon.purple{background:rgba(129,140,248,.12);color:var(--accent)}.stat-icon.green{background:rgba(52,211,153,.12);color:var(--green)}.stat-icon.amber{background:rgba(251,191,36,.12);color:var(--amber)}.stat-icon.red{background:rgba(248,113,113,.12);color:var(--red)}.stat-value{font-size:2rem;font-weight:800;letter-spacing:-.04em;font-variant-numeric:tabular-nums}.stat-label{font-size:.75rem;color:var(--text3);font-weight:500}
.section-title{font-size:1rem;font-weight:700;letter-spacing:-.02em;margin-bottom:16px}
.db-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px}.db-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:20px;cursor:pointer;transition:transform .3s var(--ease),border-color .3s,box-shadow .3s;position:relative;overflow:hidden;backdrop-filter:blur(20px);transform-style:preserve-3d}.card-enter{animation:cardIn .6s var(--ease-out)}@keyframes cardIn{from{opacity:0;transform:translateY(24px) scale(.98)}to{opacity:1;transform:translateY(0) scale(1)}}.db-card::before{content:'';position:absolute;inset:0;background:radial-gradient(400px circle at var(--mx,50%) var(--my,50%),rgba(52,211,153,.07),transparent 45%);opacity:0;transition:opacity .4s;pointer-events:none}.db-card:hover{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent),0 8px 32px var(--accentGlow)}.db-card:hover::before{opacity:1}.db-card > *{position:relative;z-index:2}.db-card-top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px;gap:8px}.db-name{font-weight:700;font-size:.95rem;font-family:'JetBrains Mono',monospace;word-break:break-all}.db-status{font-size:.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;padding:3px 8px;border-radius:4px;display:flex;align-items:center;gap:5px;flex-shrink:0}.db-status.active{background:rgba(52,211,153,.1);color:var(--green)}.db-status.active::before{content:'';width:5px;height:5px;border-radius:50%;background:var(--green);animation:pulse 2s infinite}.db-meta{display:flex;gap:16px;font-size:.72rem;color:var(--text3);margin:10px 0;flex-wrap:wrap}.db-meta span{display:flex;align-items:center;gap:4px}.db-storage-bar{height:5px;background:var(--surface3);border-radius:3px;overflow:hidden;margin:8px 0 4px}.db-storage-fill{height:100%;border-radius:3px;background:linear-gradient(90deg,var(--accent),var(--accent2));position:relative;overflow:hidden}.db-storage-fill::after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.3),transparent);animation:shimmer 2.5s infinite}@keyframes shimmer{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}}.db-storage-text{display:flex;justify-content:space-between;font-size:.65rem;color:var(--text3)}.db-actions{display:flex;gap:6px;margin-top:14px;flex-wrap:wrap}
.table-wrap{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);overflow-x:auto;backdrop-filter:blur(20px)}table{width:100%;border-collapse:collapse;min-width:640px}th{text-align:left;padding:12px 20px;font-size:.65rem;text-transform:uppercase;letter-spacing:.08em;color:var(--text3);font-weight:600;background:var(--surface2);border-bottom:1px solid var(--border);white-space:nowrap}td{padding:14px 20px;font-size:.82rem;border-bottom:1px solid var(--border);font-family:'JetBrains Mono',monospace}tr:last-child td{border-bottom:none}tbody tr{transition:background .2s}tbody tr:hover{background:rgba(129,140,248,.04)}.badge{display:inline-flex;align-items:center;gap:5px;padding:3px 10px;border-radius:20px;font-size:.68rem;font-weight:600;white-space:nowrap}.badge-green{background:rgba(52,211,153,.1);color:var(--green)}.badge-red{background:rgba(248,113,113,.1);color:var(--red)}.badge-amber{background:rgba(251,191,36,.1);color:var(--amber)}.key-actions{display:flex;gap:6px}.icon-btn{width:36px;height:36px;border-radius:8px;border:1px solid var(--border);background:var(--surface);color:var(--text2);cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all .2s var(--ease);flex-shrink:0}.icon-btn:hover{border-color:var(--accent);color:var(--accent);transform:translateY(-1px)}.icon-btn.danger:hover{border-color:var(--red);color:var(--red)}.icon-btn svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:2}
.terminal{background:rgba(8,8,10,.9);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;font-family:'JetBrains Mono',monospace;backdrop-filter:blur(20px)}.terminal-header{display:flex;align-items:center;gap:12px;padding:12px 16px;background:var(--surface2);border-bottom:1px solid var(--border)}.terminal-dots{display:flex;gap:6px}.terminal-dots span{width:10px;height:10px;border-radius:50%}.terminal-dots span:nth-child(1){background:#FF5F57}.terminal-dots span:nth-child(2){background:#FEBC2E}.terminal-dots span:nth-child(3){background:#28C840}.terminal-title{font-size:.7rem;color:var(--text3)}.terminal-body{padding:16px;height:340px;overflow-y:auto;font-size:.75rem;line-height:1.9}.log-line{display:flex;gap:12px;flex-wrap:wrap}.log-level{font-weight:700;flex-shrink:0;width:50px}.log-level.INFO{color:var(--green)}.log-level.ERROR{color:var(--red)}.log-module{color:var(--accent);flex-shrink:0}.log-msg{color:var(--text2);word-break:break-all}
.sql-input-wrap{display:flex;align-items:center;gap:8px;padding:12px 16px;background:rgba(8,8,10,.9);border:1px solid var(--border);border-radius:var(--radius-sm);transition:all .3s var(--ease)}.sql-input-wrap:focus-within{border-color:var(--accent);box-shadow:0 0 0 3px var(--accentGlow),0 0 24px var(--accentGlow)}.sql-prompt{color:var(--accent);font-weight:600;font-size:.8rem;flex-shrink:0}.sql-input{flex:1;background:none;border:none;outline:none;color:var(--text);font-family:'JetBrains Mono',monospace;font-size:.8rem;min-width:0}.sql-input::placeholder{color:var(--text3)}
.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,.65);backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;z-index:200;padding:16px}.modal-overlay.active{display:flex;animation:fadeIn .25s var(--ease)}@keyframes fadeIn{from{opacity:0}to{opacity:1}}.modal{background:var(--surface2);border:1px solid var(--border2);border-radius:20px;padding:32px;width:100%;max-width:460px;box-shadow:var(--shadow-lg),0 0 60px var(--accentGlow);animation:modalIn .4s var(--ease-out);backdrop-filter:blur(30px);position:relative;overflow:hidden;max-height:90vh;overflow-y:auto}.modal::before{content:'';position:absolute;top:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,var(--accent),var(--accent2),transparent)}@keyframes modalIn{from{opacity:0;transform:scale(.92) translateY(16px)}to{opacity:1;transform:scale(1) translateY(0)}}.modal h2{font-size:1.1rem;font-weight:700;margin-bottom:4px}.modal p{font-size:.8rem;color:var(--text3);margin-bottom:24px}.modal-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:28px;flex-wrap:wrap}
.form-input{width:100%;padding:11px 14px;background:var(--bg);border:1px solid var(--border);border-radius:10px;color:var(--text);font-size:.85rem;outline:none}.form-input:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accentGlow)}.form-label{display:block;font-size:.75rem;font-weight:600;color:var(--text2);margin-bottom:6px}.form-label .hint{color:var(--text3);font-weight:400;font-size:.68rem;margin-left:6px}.form-group{margin-bottom:18px}
.dsn-box{background:var(--bg);border:1px solid var(--border);border-radius:10px;padding:12px;font-family:'JetBrains Mono',monospace;font-size:.72rem;word-break:break-all;color:var(--accent);display:flex;gap:8px;justify-content:space-between;align-items:center;margin-bottom:10px}.dsn-box button{background:var(--surface);border:1px solid var(--border);color:var(--text2);padding:4px 10px;border-radius:6px;font-size:.65rem;cursor:pointer;flex-shrink:0}.dsn-box button:hover{color:var(--accent)}
.danger-zone{border:1px solid rgba(248,113,113,.35);border-radius:var(--radius);padding:22px;background:rgba(248,113,113,.04)}.danger-zone h3{color:var(--red);margin-bottom:6px}.danger-zone p{color:var(--text3);font-size:.85rem;margin-bottom:14px}
.arch-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:18px;margin-bottom:14px}.arch-card h3{font-size:.95rem;margin-bottom:8px;color:var(--accent)}.arch-card p{font-size:.82rem;color:var(--text2);line-height:1.6}
.flow{background:rgba(8,8,10,.95);border:1px solid var(--border);border-radius:10px;padding:16px;font-family:'JetBrains Mono',monospace;font-size:.78rem;color:var(--green);white-space:pre;overflow-x:auto;line-height:1.7}
.src-wrap{display:flex;gap:14px;flex-wrap:wrap}.src-list{width:220px;max-height:480px;overflow-y:auto;border:1px solid var(--border);border-radius:10px}.src-file{padding:9px 12px;font-size:.75rem;font-family:'JetBrains Mono',monospace;cursor:pointer;color:var(--text2);border-bottom:1px solid var(--border)}.src-file.active{color:var(--accent);background:rgba(129,140,248,.1)}.src-view{flex:1;min-width:0;max-height:480px;overflow:auto;background:rgba(8,8,10,.95);border:1px solid var(--border);border-radius:10px;padding:16px}.src-view pre{font-size:.72rem;line-height:1.6;color:#E2E8F0;white-space:pre-wrap;word-break:break-word}
.toast-container{position:fixed;bottom:24px;right:24px;z-index:400;display:flex;flex-direction:column;gap:10px}.toast{display:flex;align-items:center;gap:12px;padding:14px 20px;background:var(--surface2);border:1px solid var(--border2);border-radius:var(--radius);box-shadow:var(--shadow-lg);animation:toastIn .4s var(--ease-out);min-width:260px;max-width:420px;backdrop-filter:blur(20px)}@keyframes toastIn{from{opacity:0;transform:translateX(60px) scale(.95)}to{opacity:1;transform:translateX(0) scale(1)}}.toast-icon{width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0}.toast-icon.success{background:rgba(52,211,153,.15);color:var(--green)}.toast-icon.error{background:rgba(248,113,113,.15);color:var(--red)}.toast-icon svg{width:12px;height:12px;stroke:currentColor;fill:none;stroke-width:2.5}.toast-msg{font-size:.8rem;font-weight:500}
.empty-state{text-align:center;padding:60px 20px;color:var(--text3);grid-column:1/-1}.empty-state svg{width:48px;height:48px;stroke:var(--text3);fill:none;stroke-width:1.5;margin-bottom:16px;opacity:.5}.empty-state h3{font-size:1rem;color:var(--text2);margin-bottom:8px}.empty-state p{font-size:.8rem}
@media(max-width:1200px){.span-3{grid-column:span 6}}@media(max-width:900px){.mobile-topbar{display:flex}.sidebar{transform:translateX(-100%);width:260px;padding-top:72px}.sidebar.open{transform:translateX(0);box-shadow:20px 0 60px rgba(0,0,0,.5)}.main{margin-left:0;padding:72px 16px 32px}.span-3{grid-column:span 12}}@media(max-width:640px){html{font-size:14px}.main{padding:68px 12px 24px}.bento,.db-grid{gap:12px}.card{padding:18px}.stat-value{font-size:1.6rem}.header h1{font-size:1.35rem}.header-actions{width:100%}.header-actions .btn{flex:1;justify-content:center}.modal{padding:24px}.toast-container{left:12px;right:12px;bottom:12px}.toast{min-width:auto;width:100%}}
</style></head><body>
<canvas id="bg-canvas"></canvas><div class="grid-overlay"></div><div class="noise"></div><div class="aurora"></div>
<div class="boot" id="boot"><div class="boot-logo"><svg viewBox="0 0 24 24"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg></div><div class="boot-text">Initializing NE7-SQL</div><div class="boot-bar"><div class="boot-bar-fill" id="boot-fill"></div></div></div>
<div class="mobile-topbar" id="mobile-topbar"><button class="menu-btn" id="menu-btn"><svg viewBox="0 0 24 24"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button><div class="mobile-logo">NE7-SQL</div><div style="width:38px"></div></div>
<div class="sidebar-backdrop" id="sidebar-backdrop"></div>
<div class="screen hidden" id="screen-setup"><div class="auth-card"><h1>NE7-SQL Setup</h1><p>First run — create your admin account and connect Drime storage.</p><div class="field"><label>Admin Email</label><input id="su-email" type="email"></div><div class="field"><label>Admin Password</label><input id="su-pass" type="password"></div><div class="field"><label>Drime API Key</label><input id="su-key"></div><button class="btn btn-primary" id="su-go" style="width:100%;justify-content:center">Initialize</button><p class="switch-line">Already set up? <a id="go-login">Sign in</a></p></div></div>
<div class="screen hidden" id="screen-login"><div class="auth-card"><h1>NE7-SQL</h1><p>Sign in — admins get full control, customers get their workspace.</p><div class="field"><label>Email</label><input id="li-email" type="email"></div><div class="field"><label>Password</label><input id="li-pass" type="password"></div><button class="btn btn-primary" id="li-go" style="width:100%;justify-content:center">Sign In</button><p class="switch-line">First run? <a id="go-setup">Initialize platform</a></p></div></div>
<div class="app hidden" id="app"><aside class="sidebar" id="sidebar"><div class="logo"><div class="logo-mark"><svg viewBox="0 0 24 24"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg></div><div class="logo-text">NE7-SQL<span>Enterprise</span></div></div><div id="nav"></div><div class="sidebar-footer"><div class="status-pill"><span class="status-dot"></span>All systems operational</div></div></aside><main class="main"><div id="content"></div></main></div>
<div id="modal-root"></div><div class="toast-container" id="toasts"></div>
<script>
(function(){
'use strict';
var NL = String.fromCharCode(10);
var TOKEN = localStorage.getItem('ne7_token') || '';
var ROLE = '', NAME = '', TENANT = '';
var cachedDatabases = [];
function $(s){ return document.querySelector(s); }
function $all(s){ return document.querySelectorAll(s); }
function api(p, m, b){ var h = {'Content-Type':'application/json'}; if (TOKEN) h['Authorization'] = 'Bearer ' + TOKEN; return fetch(p, { method: m || 'GET', headers: h, body: b ? JSON.stringify(b) : undefined }).then(function(r){ return r.json(); }).catch(function(){ return null; }); }
function toast(m, t){ var c = $('#toasts'); var d = document.createElement('div'); d.className = 'toast'; var icon = t === 'error' ? '<path d="M18 6 6 18M6 6l12 12"/>' : '<path d="M20 6 9 17l-5-5"/>'; d.innerHTML = '<div class="toast-icon ' + (t === 'error' ? 'error' : 'success') + '"><svg viewBox="0 0 24 24">' + icon + '</svg></div><div class="toast-msg">' + m + '</div>'; c.appendChild(d); setTimeout(function(){ d.remove(); }, 4500); }
function modal(h){ $('#modal-root').innerHTML = '<div class="modal-overlay active"><div class="modal">' + h + '</div></div>'; $all('#modal-root [data-close]').forEach(function(b){ b.onclick = closeModal; }); }
function closeModal(){ $('#modal-root').innerHTML = ''; }
function confirmBox(t, msg, cb){ modal('<h2>' + t + '</h2><p>' + msg + '</p><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-danger" id="cfy">Confirm</button></div>'); $('#cfy').onclick = function(){ closeModal(); cb(); }; }
function copyText(t, l){ if (navigator.clipboard) { navigator.clipboard.writeText(t).then(function(){ toast((l || 'Value') + ' copied'); }); } }
function genPassword(){ var c = 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789'; var p = ''; for (var i=0;i<14;i++) p += c.charAt(Math.floor(Math.random()*c.length)); return p; }

var bootFill = $('#boot-fill');
setTimeout(function(){ if (bootFill) bootFill.style.width = '40%'; }, 100);
setTimeout(function(){ if (bootFill) bootFill.style.width = '80%'; }, 600);
setTimeout(function(){ if (bootFill) bootFill.style.width = '100%'; }, 1000);
setTimeout(function(){ $('#boot').classList.add('hidden'); }, 1400);

var canvas = $('#bg-canvas'); var ctx = canvas.getContext('2d'); var W, H, orbs = [], mx = 0, my = 0;
function rs(){ W = canvas.width = innerWidth; H = canvas.height = innerHeight; }
addEventListener('resize', rs); rs();
document.addEventListener('mousemove', function(e){ mx = (e.clientX / W - .5) * 2; my = (e.clientY / H - .5) * 2; });
orbs = [ {x:.2,y:.25,r:Math.max(W,H)*.4,c:'129,140,248',a:.10,vx:.00025,vy:.0002,p:0}, {x:.8,y:.7,r:Math.max(W,H)*.45,c:'192,132,252',a:.08,vx:-.0002,vy:.00028,p:1}, {x:.5,y:.95,r:Math.max(W,H)*.38,c:'56,189,248',a:.07,vx:.00022,vy:-.0002,p:2}, {x:.9,y:.15,r:Math.max(W,H)*.3,c:'52,211,153',a:.05,vx:-.00018,vy:.0002,p:3} ];
function drawBG(){ ctx.clearRect(0,0,W,H); var t = Date.now() * .001; for (var i=0;i<orbs.length;i++){ var o = orbs[i]; o.x += o.vx + mx*.00005; o.y += o.vy + my*.00005; if(o.x<-.1||o.x>1.1)o.vx*=-1; if(o.y<-.1||o.y>1.1)o.vy*=-1; var a = o.a + Math.sin(t + o.p)*.02; var g = ctx.createRadialGradient(o.x*W,o.y*H,0,o.x*W,o.y*H,o.r); g.addColorStop(0,'rgba('+o.c+','+a+')'); g.addColorStop(1,'rgba('+o.c+',0)'); ctx.fillStyle = g; ctx.fillRect(0,0,W,H); } requestAnimationFrame(drawBG); }
drawBG();
function attachTilt(el){ el.addEventListener('mousemove', function(e){ var r = el.getBoundingClientRect(); var x = e.clientX - r.left, y = e.clientY - r.top; var cx = r.width/2, cy = r.height/2; el.style.transform = 'perspective(900px) rotateX(' + ((y-cy)/cy*-3.5) + 'deg) rotateY(' + ((x-cx)/cx*3.5) + 'deg) translateY(-3px)'; el.style.setProperty('--mx', x + 'px'); el.style.setProperty('--my', y + 'px'); }); el.addEventListener('mouseleave', function(){ el.style.transform = ''; }); }
function attachRipple(b){ b.addEventListener('click', function(e){ var r = b.getBoundingClientRect(); var s = document.createElement('span'); s.className = 'ripple'; var sz = Math.max(r.width, r.height); s.style.width = s.style.height = sz + 'px'; s.style.left = (e.clientX - r.left - sz/2) + 'px'; s.style.top = (e.clientY - r.top - sz/2) + 'px'; b.appendChild(s); setTimeout(function(){ s.remove(); }, 600); }); }

api('/api/status').then(function(st){
  if (st && st.setup === true) {
    api('/api/me').then(function(me){ if (me && me.role) { ROLE = me.role; NAME = me.name || me.email; TENANT = me.tenantId || ''; enterApp(); } else { $('#screen-login').classList.remove('hidden'); } });
  } else if (st && st.setup === false) { $('#screen-setup').classList.remove('hidden'); }
  else { $('#screen-login').classList.remove('hidden'); }
});
$('#go-login').onclick = function(){ $('#screen-setup').classList.add('hidden'); $('#screen-login').classList.remove('hidden'); };
$('#go-setup').onclick = function(){ $('#screen-login').classList.add('hidden'); $('#screen-setup').classList.remove('hidden'); };
$('#su-go').onclick = function(){ api('/api/setup','POST',{ adminEmail: $('#su-email').value, adminPassword: $('#su-pass').value, drimeKey: $('#su-key').value }).then(function(r){ if (r && r.ok) { toast('Initialized! Sign in.'); $('#screen-setup').classList.add('hidden'); $('#screen-login').classList.remove('hidden'); } else { toast((r && r.error) || 'Failed', 'error'); } }); };
$('#li-go').onclick = function(){ api('/api/login','POST',{ email: $('#li-email').value, password: $('#li-pass').value }).then(function(r){ if (r && r.token) { TOKEN = r.token; ROLE = r.role; NAME = r.name || r.email; TENANT = r.tenantId || ''; localStorage.setItem('ne7_token', TOKEN); enterApp(); } else { toast((r && r.error) || 'Login failed', 'error'); } }); };
$('#menu-btn').onclick = function(){ $('#sidebar').classList.add('open'); $('#sidebar-backdrop').classList.add('active'); };
$('#sidebar-backdrop').onclick = function(){ $('#sidebar').classList.remove('open'); $('#sidebar-backdrop').classList.remove('active'); };

function enterApp(){
  $('#screen-setup').classList.add('hidden'); $('#screen-login').classList.add('hidden');
  $('#app').classList.remove('hidden'); $('#mobile-topbar').classList.remove('hidden');
  buildNav(); nav(ROLE === 'admin' ? 'overview' : 'databases');
}
function buildNav(){
  var items = ROLE === 'admin'
    ? [['overview','Overview','grid'],['databases','Databases','db'],['keys','API Keys','key'],['admins','Admins','users'],['customers','Customers','user'],['console','SQL Console','term'],['panel','NE7 Panel','panel'],['settings','Settings','gear']]
    : [['databases','My Databases','db'],['console','SQL Console','term']];
  var icons = { grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/>', db:'<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>', key:'<path d="m21 2-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0 3 3L22 7l-3-3"/>', users:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/>', user:'<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>', term:'<polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/>', panel:'<rect x="3" y="3" width="18" height="18" rx="2"/><line x1="9" y1="3" x2="9" y2="21"/>', gear:'<circle cx="12" cy="12" r="3"/><path d="M12 1v4M12 19v4M4.2 4.2l2.8 2.8M17 17l2.8 2.8M1 12h4M19 12h4M4.2 19.8 7 17M17 7l2.8-2.8"/>' };
  $('#nav').innerHTML = items.map(function(i){ return '<div class="nav-item" data-v="' + i[0] + '"><svg viewBox="0 0 24 24">' + icons[i[2]] + '</svg>' + i[1] + '</div>'; }).join('') + '<div class="nav-item" id="logout" style="color:var(--red)"><svg viewBox="0 0 24 24"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>Logout</div>';
  $all('.nav-item').forEach(function(n){ n.onclick = function(){ if (n.id === 'logout') { localStorage.removeItem('ne7_token'); location.reload(); } nav(n.getAttribute('data-v')); }; });
  $all('.btn').forEach(attachRipple);
}
function nav(v){
  $all('.nav-item').forEach(function(n){ n.classList.toggle('active', n.getAttribute('data-v') === v); });
  $('#sidebar').classList.remove('open'); $('#sidebar-backdrop').classList.remove('active');
  if (v === 'overview') vOverview(); else if (v === 'databases') vDatabases(); else if (v === 'keys') vKeys(); else if (v === 'admins') vAdmins(); else if (v === 'customers') vCustomers(); else if (v === 'console') vConsole(); else if (v === 'panel') vPanel(); else if (v === 'settings') vSettings();
}

function vOverview(){
  api('/api/admin/storage').then(function(s){ if (!s) return;
    $('#content').innerHTML = '<div class="header"><h1>Overview</h1><div class="header-actions"><button class="btn btn-primary" id="ov-new"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Create Database</button></div></div><div class="bento">'
      + '<div class="card span-3 stat-card"><div class="stat-header"><div class="stat-icon purple"><svg viewBox="0 0 24 24"><path d="m21 2-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777z"/></svg></div></div><div><div class="stat-value">' + s.rows.length + '</div><div class="stat-label">API Keys</div></div></div>'
      + '<div class="card span-3 stat-card"><div class="stat-header"><div class="stat-icon green"><svg viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg></div></div><div><div class="stat-value">' + s.grandTotalGB + '<span style="font-size:1rem;color:var(--text3)"> GB</span></div><div class="stat-label">Grand Total</div></div></div>'
      + '<div class="card span-3 stat-card"><div class="stat-header"><div class="stat-icon amber"><svg viewBox="0 0 24 24"><path d="M13 2 3 14h9l-1 8 10-12h-9l1-8z"/></svg></div></div><div><div class="stat-value">' + s.grandUsedGB + '<span style="font-size:1rem;color:var(--text3)"> GB</span></div><div class="stat-label">Grand Used</div></div></div>'
      + '<div class="card span-3 stat-card"><div class="stat-header"><div class="stat-icon red"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg></div></div><div><div class="stat-value">' + s.grandBalanceGB + '<span style="font-size:1rem;color:var(--text3)"> GB</span></div><div class="stat-label">Grand Balance</div></div></div>'
      + '<div class="card span-12"><div class="section-title">Storage per API Key</div><div class="table-wrap"><table><tr><th>Key</th><th>Status</th><th>Capacity</th><th>Used</th><th>Balance</th></tr>' + s.rows.map(function(r){ return '<tr><td style="font-family:Inter;font-weight:600">' + r.nickname + '</td><td><span class="badge ' + (r.status==='HEALTHY'?'badge-green':'badge-red') + '">' + r.status + '</span></td><td>' + r.capacityGB + ' GB</td><td>' + r.usedGB + ' GB</td><td>' + r.balanceGB + ' GB</td></tr>'; }).join('') + '</table></div></div></div>';
    var b = $('#ov-new'); if (b) { attachRipple(b); b.onclick = openCreateDb; }
    $all('.card').forEach(attachTilt);
  });
}

function vDatabases(){
  api('/api/databases').then(function(dbs){ cachedDatabases = dbs || [];
    var html = '<div class="header"><h1>' + (ROLE === 'admin' ? 'All Databases' : 'My Databases') + '</h1>' + (ROLE === 'admin' ? '<div class="header-actions"><button class="btn btn-primary" id="new-db"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Create Database</button></div>' : '') + '</div><div class="db-grid">';
    if (!cachedDatabases.length) html += '<div class="empty-state"><svg viewBox="0 0 24 24"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg><h3>' + (ROLE === 'admin' ? 'No databases yet' : 'No databases assigned') + '</h3><p>' + (ROLE === 'admin' ? 'Create your first isolated database.' : 'Your admin has not assigned a database yet.') + '</p></div>';
    cachedDatabases.forEach(function(db){
      var maxMB = db.maxSizeMB || 5120; var usedMB = db.usedMB || 0; var pct = Math.min((usedMB / maxMB) * 100, 100);
      html += '<div class="db-card card-enter"><div class="db-card-top"><div class="db-name">' + db.name + '</div><div class="db-status active">Active</div></div>'
        + (ROLE === 'admin' ? (db.ownerEmail ? '<div><span class="badge badge-amber">Assigned: ' + db.ownerEmail + '</span></div>' : '<div><span class="badge" style="background:var(--surface3);color:var(--text3)">Unassigned</span></div>') : '')
        + '<div class="db-meta"><span>' + db.tables + ' tables</span><span>key: ' + (db.key || '-') + '</span></div>'
        + '<div class="db-storage-bar"><div class="db-storage-fill" style="width:' + pct + '%"></div></div><div class="db-storage-text"><span>' + (usedMB/1024).toFixed(2) + ' GB used</span><span>' + (maxMB/1024).toFixed(1) + ' GB limit</span></div>'
        + (ROLE === 'admin' ? '<div class="db-actions"><button class="btn btn-amber btn-sm" data-topup="' + db.tenantId + '">Top Up</button><button class="btn btn-ghost btn-sm" data-assign="' + db.tenantId + '">Assign</button><button class="btn btn-danger btn-sm" data-del="' + db.tenantId + '" data-name="' + db.name + '">Delete</button></div>' : '<div class="db-actions"><button class="btn btn-ghost btn-sm" data-use="' + db.tenantId + '">Open Console</button></div>')
        + '</div>';
    });
    html += '</div>';
    $('#content').innerHTML = html;
    var nb = $('#new-db'); if (nb) { attachRipple(nb); nb.onclick = openCreateDb; }
    $all('.db-card').forEach(attachTilt);
    $all('[data-topup]').forEach(function(b){ attachRipple(b); b.onclick = function(){ openTopup(b.getAttribute('data-topup')); }; });
    $all('[data-assign]').forEach(function(b){ attachRipple(b); b.onclick = function(){ openAssign(b.getAttribute('data-assign')); }; });
    $all('[data-del]').forEach(function(b){ attachRipple(b); b.onclick = function(){ var id = b.getAttribute('data-del'); var nm = b.getAttribute('data-name'); confirmBox('Delete ' + nm + '?', 'This permanently removes the database and all its data.', function(){ api('/api/admin/customers/' + id, 'DELETE').then(function(){ toast('Deleted'); vDatabases(); }); }); }; });
    $all('[data-use]').forEach(function(b){ attachRipple(b); b.onclick = function(){ nav('console'); var s = $('#sql-db'); if (s) s.value = b.getAttribute('data-use'); }; });
  });
}

function openCreateDb(){
  api('/api/admin/customers').then(function(cs){ cs = cs || [];
    modal('<h2>Create Isolated Database</h2><p>Each DB is a fully isolated tenant with its own credentials.</p><div class="form-group"><label class="form-label">Database Nickname</label><input class="form-input" id="db-name" placeholder="acme-analytics"></div><div class="form-group"><label class="form-label">Initial Storage (GB)</label><input class="form-input" id="db-size" type="number" value="5" min="1" max="20"></div><div class="form-group"><label class="form-label">Assign to Customer <span class="hint">optional</span></label><select class="form-input" id="db-assign"><option value="">- Unassigned -</option>' + cs.map(function(c){ return '<option value="' + c.id + '" data-email="' + c.email + '">' + c.name + ' (' + c.email + ')</option>'; }).join('') + '</select></div><div class="form-group"><label class="form-label">Password <span class="hint">blank = auto</span></label><input class="form-input" id="db-pass"></div><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="db-go">Create + Provision</button></div>');
    $('#db-go').onclick = function(){
      var name = $('#db-name').value.trim(); if (!name) { toast('Name required', 'error'); return; }
      var pass = $('#db-pass').value || genPassword();
      var sel = $('#db-assign'); var opt = sel.selectedOptions[0];
      var btn = $('#db-go'); btn.disabled = true; btn.textContent = 'Provisioning...';
      api('/api/admin/customers','POST',{ name: name, email: (opt && opt.getAttribute('data-email')) || (name.toLowerCase().replace(/[^a-z0-9]/g,'') + '@internal.ne7'), password: pass, storageGB: parseInt($('#db-size').value) || 5 }).then(function(r){
        btn.disabled = false; btn.textContent = 'Create + Provision';
        if (r && r.ok) { closeModal(); showCreds(name, r.tenantId || name, pass, r.dsn); pollDatabases(0); }
        else { toast((r && r.error) || 'Failed', 'error'); }
      });
    };
  });
}
function showCreds(name, tenant, pass, dsn){
  modal('<h2>Database Created</h2><p>Save these credentials now. This database is fully isolated.</p><div class="dsn-box"><span>Tenant: ' + tenant + '</span></div><div class="dsn-box"><span>Password: ' + pass + '</span><button id="cp-pass">Copy</button></div><div class="dsn-box"><span style="word-break:break-all">' + (dsn || ('postgresql://' + tenant + ':***@ne7-sql.workers.dev:5432/' + tenant)) + '</span><button id="cp-dsn">Copy</button></div><div class="modal-actions"><button class="btn btn-primary" data-close>Done</button></div>');
  $('#cp-pass').onclick = function(){ copyText(pass, 'Password'); };
  $('#cp-dsn').onclick = function(){ copyText(dsn || ('postgresql://' + tenant + ':***@ne7-sql.workers.dev:5432/' + tenant), 'DSN'); };
}
function pollDatabases(n){ vDatabases(); if (n < 5) setTimeout(function(){ pollDatabases(n + 1); }, 1500); }
function openTopup(tid){
  modal('<h2>Top Up Storage</h2><div class="form-group"><label class="form-label">Add Storage (GB)</label><input class="form-input" id="tu-amt" type="number" value="5" min="1" max="20"></div><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="tu-go">Top Up</button></div>');
  $('#tu-go').onclick = function(){ api('/api/admin/databases/' + tid + '/topup','POST',{ amountGB: parseInt($('#tu-amt').value) || 5 }).then(function(r){ if (r && r.ok) { closeModal(); toast('Topped up'); vDatabases(); } else { toast((r && r.error) || 'Failed', 'error'); } }); };
}
function openAssign(tid){
  api('/api/admin/customers').then(function(cs){ cs = cs || [];
    modal('<h2>Assign Database</h2><div class="form-group"><label class="form-label">Assign to Customer</label><select class="form-input" id="as-cust"><option value="">- Unassign -</option>' + cs.map(function(c){ return '<option value="' + c.id + '">' + c.name + ' (' + c.email + ')</option>'; }).join('') + '</select></div><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="as-go">Assign</button></div>');
    $('#as-go').onclick = function(){ api('/api/admin/databases/' + tid + '/assign','POST',{ customerId: $('#as-cust').value }).then(function(r){ if (r && r.ok) { closeModal(); toast('Assigned'); vDatabases(); } else { toast((r && r.error) || 'Failed', 'error'); } }); };
  });
}

function vKeys(){
  api('/api/admin/keys').then(function(ks){ if (!ks) return;
    $('#content').innerHTML = '<div class="header"><h1>API Keys</h1><div class="header-actions"><button class="btn btn-primary" id="add-key"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Add Key</button></div></div><div class="table-wrap"><table><tr><th>Nickname</th><th>API Key</th><th>Status</th><th>Capacity</th><th>Actions</th></tr>' + ks.map(function(k){ return '<tr><td style="font-family:Inter;font-weight:600">' + k.nickname + '</td><td class="key-text">' + k.key + '</td><td><span class="badge ' + (k.status==='HEALTHY'?'badge-green':'badge-red') + '">' + (k.status || 'UNKNOWN') + '</span></td><td>' + k.capacityGB + ' GB</td><td><div class="key-actions"><button class="icon-btn" data-eye="' + k.id + '"><svg viewBox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg></button><button class="icon-btn" data-copy="' + k.id + '"><svg viewBox="0 0 24 24"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="icon-btn danger" data-delkey="' + k.id + '" data-nick="' + k.nickname + '"><svg viewBox="0 0 24 24"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>'; }).join('') + '</table></div>';
    var b = $('#add-key'); attachRipple(b); b.onclick = function(){ modal('<h2>Add Drime API Key</h2><div class="form-group"><label class="form-label">Nickname</label><input class="form-input" id="k-nick"></div><div class="form-group"><label class="form-label">API Key</label><input class="form-input" id="k-val"></div><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="k-go">Add Key</button></div>'); $('#k-go').onclick = function(){ api('/api/admin/keys','POST',{ nickname: $('#k-nick').value, key: $('#k-val').value }).then(function(r){ if (r && r.ok) { closeModal(); toast('Key added'); vKeys(); } else { toast((r && r.error) || 'Failed', 'error'); } }); }; };
    $all('[data-eye]').forEach(function(b){ b.onclick = function(){ var id = b.getAttribute('data-eye'); var row = b.closest('tr'); var cell = row.querySelector('.key-text'); if (cell.getAttribute('data-rev')) { cell.textContent = cell.getAttribute('data-mask'); cell.removeAttribute('data-rev'); } else { api('/api/admin/keys/' + id + '/reveal').then(function(r){ if (r && r.key) { cell.setAttribute('data-mask', cell.textContent); cell.textContent = r.key; cell.setAttribute('data-rev','1'); } }); } }; });
    $all('[data-copy]').forEach(function(b){ b.onclick = function(){ api('/api/admin/keys/' + b.getAttribute('data-copy') + '/reveal').then(function(r){ if (r && r.key) copyText(r.key, 'API Key'); }); }; });
    $all('[data-delkey]').forEach(function(b){ b.onclick = function(){ confirmBox('Remove ' + b.getAttribute('data-nick') + '?', 'This key is removed from the pool.', function(){ api('/api/admin/keys/' + b.getAttribute('data-delkey'), 'DELETE').then(function(){ toast('Removed'); vKeys(); }); }); }; });
  });
}
function vAdmins(){
  api('/api/admin/admins').then(function(l){ if (!l) return;
    $('#content').innerHTML = '<div class="header"><h1>Admins</h1><div class="header-actions"><button class="btn btn-primary" id="add-admin"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Add Admin</button></div></div><div class="table-wrap"><table><tr><th>Email</th><th>Actions</th></tr>' + l.map(function(e){ return '<tr><td style="font-family:Inter;font-weight:600">' + e + '</td><td><button class="icon-btn danger" data-deladmin="' + encodeURIComponent(e) + '"><svg viewBox="0 0 24 24"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr>'; }).join('') + '</table></div>';
    var b = $('#add-admin'); attachRipple(b); b.onclick = function(){ modal('<h2>Add Admin</h2><div class="form-group"><label class="form-label">Email</label><input class="form-input" id="a-email"></div><div class="form-group"><label class="form-label">Password</label><input class="form-input" id="a-pass"></div><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="a-go">Add Admin</button></div>'); $('#a-go').onclick = function(){ api('/api/admin/admins','POST',{ email: $('#a-email').value, password: $('#a-pass').value }).then(function(r){ if (r && r.ok) { closeModal(); toast('Admin added'); vAdmins(); } }); }; };
    $all('[data-deladmin]').forEach(function(b){ b.onclick = function(){ confirmBox('Remove admin?', 'This admin loses access.', function(){ api('/api/admin/admins/' + b.getAttribute('data-deladmin'), 'DELETE').then(function(){ toast('Removed'); vAdmins(); }); }); }; });
  });
}
function vCustomers(){
  api('/api/admin/customers').then(function(cs){ cs = cs || [];
    api('/api/databases').then(function(dbs){ dbs = dbs || [];
      $('#content').innerHTML = '<div class="header"><h1>Customers</h1><div class="header-actions"><button class="btn btn-primary" id="add-cust"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Add Customer</button></div></div><div class="table-wrap"><table><tr><th>Name</th><th>Email</th><th>Tenant</th><th>DBs</th><th>Actions</th></tr>' + cs.map(function(c){ var n = dbs.filter(function(d){ return d.tenantId === c.tenantId; }).length; return '<tr><td style="font-family:Inter;font-weight:600">' + c.name + '</td><td>' + c.email + '</td><td style="color:var(--text3)">' + c.tenantId + '</td><td><span class="badge badge-amber">' + n + '</span></td><td><button class="icon-btn danger" data-delcust="' + c.id + '"><svg viewBox="0 0 24 24"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr>'; }).join('') + '</table></div>';
      var b = $('#add-cust'); attachRipple(b); b.onclick = function(){ modal('<h2>Add Customer</h2><div class="form-group"><label class="form-label">Name</label><input class="form-input" id="c-name"></div><div class="form-group"><label class="form-label">Email</label><input class="form-input" id="c-email"></div><div class="form-group"><label class="form-label">Password</label><input class="form-input" id="c-pass"></div><div class="modal-actions"><button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="c-go">Create Customer</button></div>'); $('#c-go').onclick = function(){ api('/api/admin/customers','POST',{ name: $('#c-name').value, email: $('#c-email').value, password: $('#c-pass').value }).then(function(r){ if (r && r.ok) { closeModal(); toast('Customer created'); vCustomers(); } else { toast((r && r.error) || 'Failed', 'error'); } }); }; };
      $all('[data-delcust]').forEach(function(b){ b.onclick = function(){ confirmBox('Delete customer?', 'Their access is removed; DBs become unassigned.', function(){ api('/api/admin/customers/' + b.getAttribute('data-delcust'), 'DELETE').then(function(){ toast('Deleted'); vCustomers(); }); }); }; });
    });
  });
}
function vConsole(){
  $('#content').innerHTML = '<div class="header"><h1>SQL Console</h1></div><div class="terminal"><div class="terminal-header"><div class="terminal-dots"><span></span><span></span><span></span></div><div class="terminal-title">psql — ' + (ROLE === 'admin' ? 'ne7sql' : TENANT) + '</div></div><div class="terminal-body" id="term"><div class="log-line"><span class="log-msg" style="color:var(--green)">Connected to NE7-SQL Enterprise</span></div></div><div style="padding:12px 16px;border-top:1px solid var(--border)"><div class="sql-input-wrap"><span class="sql-prompt">ne7sql=#</span>' + (ROLE === 'admin' ? '<input class="sql-input" id="sql-db" placeholder="tenant" style="max-width:140px">' : '') + '<input class="sql-input" id="sql-input" placeholder="SELECT * FROM ..."><button class="btn btn-primary btn-sm" id="sql-run">Run</button></div></div></div>';
  function run(){ var s = $('#sql-input').value.trim(); if (!s) return; var t = ROLE === 'admin' ? (($('#sql-db') && $('#sql-db').value.trim()) || '') : TENANT; if (!t) { toast('No tenant selected', 'error'); return; } if (ROLE !== 'admin' && t !== TENANT) { toast('Access denied', 'error'); return; } $('#term').innerHTML += '<div class="log-line"><span class="log-module">' + t + '=#</span><span class="log-msg">' + s + '</span></div>'; $('#sql-input').value = ''; api('/api/query','POST',{ sql: s, tenantId: t }).then(function(r){ if (!r) return; $('#term').innerHTML += '<div class="log-line"><span class="log-level ' + (r.error ? 'ERROR' : 'INFO') + '">' + (r.error || r.message || 'OK') + '</span><span class="log-msg">' + (r.rows ? NL + JSON.stringify(r.rows.slice(0,10), null, 1) : '') + '</span></div>'; $('#term').scrollTop = 1e9; }); }
  var rb = $('#sql-run'); attachRipple(rb); rb.onclick = run; $('#sql-input').onkeydown = function(e){ if (e.key === 'Enter') run(); };
}
function vPanel(){
  $('#content').innerHTML = '<div class="header"><h1>NE7 Panel — Full Stack</h1></div><div class="arch-card"><h3>Architecture (CF + Drime)</h3><p><b>Cloudflare Worker</b> = the brain. <b>KV</b> = keyring (Drime keys, admins, customers, signing secret). <b>Drime</b> = warehouse (customer data). Zero VPS.</p></div><div class="arch-card"><h3>Inverted Postgres</h3><p>TCP socket lives client-side. The Hyperwire Agent binds localhost:5432 and tunnels Postgres wire bytes over WebSocket to the Worker.</p><div class="flow">[psql / DBeaver]' + NL + '   |  TCP (localhost:5432)' + NL + '   v' + NL + '[Hyperwire Agent]' + NL + '   |  WebSocket' + NL + '   v' + NL + '[CF Worker /cable] -&gt; Executor -&gt; Drime</div></div><div class="arch-card"><h3>Full Source Code</h3><p>Every file that powers this platform.</p><div class="src-wrap"><div class="src-list" id="src-list"></div><div class="src-view"><pre id="src-code">Select a file...</pre></div></div></div>';
  api('/api/admin/source').then(function(src){ if (!src) return; var names = Object.keys(src); $('#src-list').innerHTML = names.map(function(n){ return '<div class="src-file" data-f="' + n + '">' + n + '</div>'; }).join(''); $all('.src-file').forEach(function(f){ f.onclick = function(){ $all('.src-file').forEach(function(x){ x.classList.remove('active'); }); f.classList.add('active'); $('#src-code').textContent = src[f.getAttribute('data-f')]; }; }); });
}
function vSettings(){
  $('#content').innerHTML = '<div class="header"><h1>Settings</h1></div><div class="danger-zone"><h3>Danger Zone</h3><p>Reset wipes all databases and customers from Drime, but keeps admins and API keys. Cannot be undone.</p><button class="btn btn-danger" id="reset-btn">Reset Platform</button></div>';
  var b = $('#reset-btn'); attachRipple(b); b.onclick = function(){ confirmBox('Confirm Reset', 'Type RESET in the next prompt to wipe everything.', function(){ var w = prompt('Type RESET to confirm'); if (w === 'RESET') { api('/api/admin/reset','POST',{}).then(function(r){ toast('Deleted ' + ((r && r.deleted) || 0) + ' files.'); vOverview(); }); } else { toast('Aborted'); } }); };
}
})();
</script></body></html>`;
